"""
Test script for image processing without running the Telegram bot.

Usage:
    python scripts/test_ocr.py                           # Process all in sample_images/
    python scripts/test_ocr.py path/to/image.jpg         # Process a single image
    python scripts/test_ocr.py path/to/folder/            # Process all in a folder
    python scripts/test_ocr.py --generate-ground-truth   # Create tests/ground_truth.yaml from OCR
"""

import sys
import logging
from pathlib import Path

# Setup logging - use DEBUG level to see OCR details
logging.basicConfig(
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
    level=logging.DEBUG,
)
logger = logging.getLogger(__name__)

# Reduce noise from other libraries
logging.getLogger("PIL").setLevel(logging.WARNING)
logging.getLogger("pytesseract").setLevel(logging.WARNING)

# Import after logging setup
import yaml
from src.services.image_processor import process_schedule_image

# Default paths (relative to project root = parent of scripts/)
SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parent
GROUND_TRUTH_PATH = PROJECT_ROOT / "tests" / "raw_ground_truth.yaml"


def schedule_to_ground_truth_entries(schedule: list[dict]) -> list[dict[str, str]]:
    """Convert schedule from process_schedule_image to ground truth YAML format."""
    return [
        {"date": entry["date"].isoformat(), "shift": entry["shift"]}
        for entry in schedule
    ]


def generate_ground_truth_yaml(
    images_dir: Path,
    output_path: Path,
) -> None:
    """
    Run OCR on all images in images_dir and write results to output_path
    in ground_truth.yaml format. You can then edit the file to fix any OCR errors.
    """
    image_extensions = {".jpg", ".jpeg", ".png", ".webp"}
    images = sorted(
        f for f in images_dir.iterdir()
        if f.suffix.lower() in image_extensions
    )
    if not images:
        print(f"❌ No images found in: {images_dir}")
        sys.exit(1)

    data = {}
    for image_path in images:
        print(f"Processing {image_path.name}...")
        try:
            schedule = process_schedule_image(image_path.read_bytes())
            data[image_path.name] = schedule_to_ground_truth_entries(schedule)
            print(f"  → {len(schedule)} shifts")
        except Exception as e:
            print(f"  ❌ Error: {e}")
            logger.exception("Traceback:")

    header = (
        "# Ground truth for OCR accuracy tests.\n"
        "# Generated by: python scripts/test_ocr.py --generate-ground-truth\n"
        "# Edit dates/shifts below to match the real schedule, then run: pytest tests/test_ocr_accuracy.py -v\n"
        "#\n"
    )
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(header)
        yaml.dump(data, f, default_flow_style=False, allow_unicode=True, sort_keys=False)
    print(f"\n✅ Wrote {output_path}")
    print("   Edit the file to correct any wrong dates/shifts, then run: pytest tests/test_ocr_accuracy.py -v")


def process_single_image(image_path: Path) -> None:
    """Process a single image and print results."""
    print(f"\n{'='*60}")
    print(f"Processing: {image_path.name}")
    print('='*60)
    
    # Read image bytes
    image_bytes = image_path.read_bytes()
    
    # Process
    try:
        schedule = process_schedule_image(image_bytes)
        
        if schedule:
            print(f"\n✅ Found {len(schedule)} shifts:")
            for entry in schedule:
                shift_date = entry["date"]
                shift_code = entry["shift"]
                shift_info = entry.get("shift_info", {})
                shift_name = shift_info.get("name", "?")
                print(f"  • {shift_date.strftime('%a %d %b')}: {shift_code} ({shift_name})")
        else:
            print("\n❌ No shifts found in image")
            
    except Exception as e:
        print(f"\n❌ Error processing image: {e}")
        logger.exception("Full traceback:")


def main() -> None:
    """Main entry point."""
    argv = sys.argv[1:]
    if "--generate-ground-truth" in argv:
        argv.remove("--generate-ground-truth")
        images_dir = Path(argv[0]) if argv else PROJECT_ROOT / "sample_images"
        if not images_dir.exists():
            print(f"❌ Path not found: {images_dir}")
            sys.exit(1)
        if not images_dir.is_dir():
            images_dir = images_dir.parent
        generate_ground_truth_yaml(images_dir, GROUND_TRUTH_PATH)
        return

    # Determine input path
    if argv:
        input_path = Path(argv[0])
    else:
        input_path = PROJECT_ROOT / "sample_images"
    
    if not input_path.exists():
        print(f"❌ Path not found: {input_path}")
        print("\nUsage:")
        print("  python scripts/test_ocr.py                    # Process all in sample_images/")
        print("  python scripts/test_ocr.py image.jpg         # Process single image")
        print("  python scripts/test_ocr.py folder/           # Process all in folder")
        print("  python scripts/test_ocr.py --generate-ground-truth   # Create tests/ground_truth.yaml")
        sys.exit(1)
    
    # Collect images to process
    image_extensions = {".jpg", ".jpeg", ".png", ".webp"}
    
    if input_path.is_file():
        images = [input_path]
    else:
        images = [
            f for f in input_path.iterdir()
            if f.suffix.lower() in image_extensions
        ]
        images.sort()
    
    if not images:
        print(f"❌ No images found in: {input_path}")
        sys.exit(1)
    
    print(f"Found {len(images)} image(s) to process")
    
    # Process each image
    for image_path in images:
        process_single_image(image_path)
    
    print(f"\n{'='*60}")
    print("Done!")
    print("Check debug/ folder for cell images (if DEBUG_SAVE_CELLS=true)")


if __name__ == "__main__":
    main()
